---
- name: Update apt repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install utility packages
  apt:
    name:
      - curl
      - tar
      - unzip
      - jq
    state: present

- name: Download Node Exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"

- name: Unarchive Node Exporter
  unarchive:
    src: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Copy Node Exporter binary to bin directory
  copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes

- name: Create systemd service file for Node Exporter
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=nobody
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/node_exporter.service"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable Node Exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
